### PR TITLE
Implements #34 (and a bug fix)

### PR DESCRIPTION
**Pull request by kbknapp**
This PR adds a `-o <file>` and `--outfile <file>` as well as a `outfile = "myfile.md"` to the `.clog.toml`

### CODE REVIEW

**Comment by cburgdorf** [comment]
Thanks for all the great work!  For streamlined ergonomics, shouldn't we call it `outfile` in the config file as well?

**Comment by kbknapp** [comment]
:+1: , good call. It's been changed ;)

**Comment by kbknapp** [comment]
Sorry, had to rebase to fix the commit message and keep the changes on the correct commit!

**Comment by kbknapp** [comment]
Rebase is done - should be safe to merge now.

**Comment by cburgdorf** [comment]
Thanks :+1:  just landed :)

**Pull request merged**
