### PR TITLE
feat(build): add travis-ci support

### PR DESCRIPTION
**Pull request by kbknapp**

### CODE REVIEW

**Comment by kbknapp** [comment]
@cburgdorf If you're interested we could add Travis-CI support. This would require some steps be completed in the `clog` repo settings page in addition to this PR.

Follow:
http://docs.travis-ci.com/user/getting-started/

**Comment by cburgdorf** [comment]
We still need to setup a webhook, right?

**Comment by cburgdorf** [comment]
Done ;)

https://travis-ci.org/thoughtram/clog

**Comment by kbknapp** [comment]
Sorry, didn't see the question until just a second ago, but looks like you got it! Awesome! :)

**Pull request merged**
