### PR TITLE
feat: implements better errors, abstract writers, and defaults to stdout

### LINKED ISSUE #55: ui/ux(cli): create and update message
This is really just for better UX:

Whenever I **create** or update a changelog with `clog` the output I get is always:

```
$ changelog updated (took xx ms)
```

I  think it'd be nicer if the tools states that it **created** a changelog, if that's the case and only **updates** if **that's** the case.

### LINKED ISSUE #57: feat(writer): add writer abstraction so they can be swapped out
Clog creates and writes markdown files by default. I think there are also use cases, where don't want markdown as output, but rather JSON. It'd be cool if we could plug in any writer, as long as it implements a certain interface. The writer could then be configurable through `.clog.toml` and cli options.

`LogWriter` would then just be another writer that can be plugged into clog.

@kbknapp @cburgdorf wdyt?

### LINKED ISSUE #58: chore: clog should write to stdout
Currently, clog creates a markdown file by default. As discussed in https://github.com/thoughtram/clog/issues/57, I think it'd make sense if writers could be swapped out.

This raises my next question: Unix commands usually write to stdout by default. If we implement a writer abstraction, so we can plug more into clog, we shouldn't prefer one over the other. Which brings me to the point, that it might be better if `clog` writes to stdout by default.

Of course, this adds the complexity that you always have to provide a writer option in case you don't want to write to stdout, but this is how most/all UNIX commands work.

Thoughts on this?

### LINKED ISSUE #62: chore: add more default sections
Currently we ship with only `Bug Fixes` and `Features` the [angular conventions](https://github.com/ajoslin/conventional-changelog/blob/38e3faa7dcff12bb057b781745b7253cf1bd8be2/conventions/angular.md) we link to uses quite a few more sections as well. It'd be nice to ship with a few more of the default sections, perhaps not all of them, but at least a few that are nice to display in a changelog (such as performance, test, docs, etc.)

### LINKED ISSUE #63: Should clog allow reading old changelog without writing to it?
With the new #64 PR I realized that `clog` cannot currently read an old changelog and save to a new location. **If** it reads from an old changelog, it *always* writes back out to that location. It may be useful to allow reading from an old changelog and outputting to a new one, or arbitrary location.

Imagine wanting to run `clog` and suck up all the old data, but output to `stdout`? Currently you can't. It either reads everything from the old one, and writes back out to it, or doesn't read the old one and prints to `stdout`.

What do you think?

### PR DESCRIPTION
**Pull request by kbknapp**
Closes #55
Closes #57
Closes #58
Closes #62 
Closes #63 

~~**WIP: DO NOT MERGE**~~

This PR does a few things:
 * It creates a new abstraction layer which can be used to write changelogs of arbitrary formats provided you implement the `clog::fmt::FormatWriter` trait. Currently there is only two implementing structs `MarkdownWriter` and `JsonWriter`. ~~Also, it's not user selectable from the CLI (yet)~~, only when using the lib.
 * It also now defaults to printing to `stdout` unless there is an `outfile` field in the `.clog.toml` (or whatever config) *or* the user passes in the `-o <file>` option. ~~(See #64 for some oddities I noticed)~~
 * The `Changelog updated [ snip ]` has been changed to `Changelog written (took X ms)` to be created/updated agnostic. And also this only gets printed now when the changelog is **not** written to stdout.
 * Finally, it begins the basis for vastly improved errors, and writes all errors to stderr like a good unix tool :) 

Because of some of the changes, this PR is a **BREAKING CHANGE** (although not drastically). Because a solid 1.0 release is fast approaching, this shouldn't be an issue.

To do before merge:
- [x] Write update docs, since some items have changed
- [x] Write docs for new items
- [x] Implement a Json writer
- [ ] ~~Implement an Html writer?~~
- [x] Update README.md with any changes
- [x] Test
- [x] Rebuild docs
- [x] Decide on #63 and implement
- [x] Test the idea of Implementing something closer to an AST than trait based formats...

There's a few places I think could be implemented in a more clean fashion as well, depending on how the testing goes I may make some minor changes.

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Love that work @kbknapp ! Thank you for pushing on all edges! :heart:

**Comment by PascalPrecht** [comment]
I think the HTML writer can be left out on this PR, since we have to discuss, what the HTML needs to look like (or would we just blindly do what a markdown2html transformer outputs?). Other then that, thanks for pushing this!

**Comment by kbknapp** [comment]
Good point :+1:

**Comment by kbknapp** [comment]
I just added a json writer with a `-T` option to output in either JSON or Markdown. 

The "catch" is at the present it only outputs *new* changelog data in that format. I.e. if you set an input file that is markdown, but set the output to JSON you'll get all the new items in JSON and old data in markdown. The way to change that is very, *very*, **very** involved. Personally I don't think it's worth the effort because the "fix" from the user standpoint is extremely quite simple, use the `--from`. Plus I don't think users would have a huge need to input one format and output another.

**Comment by kbknapp** [comment]
Sample output of the JSON...

In parkdown it would look like this:

```html
$ clog
<a name=""></a>
##  (2015-07-24)


#### Features

*   implements a json writer output format ([622770bf](https://github.com/thoughtram/clog/commit/622770bff00cc95f2dfe8136e672681534d1acc1))
*   adds performance as a default section ([50034322](https://github.com/thoughtram/clog/commit/5003432279027b5ce4389a53baceb2f9fa790d20), closes [#62](https://github.com/thoughtram/clog/issues/62))
*   allows reading old changelog data from one file and outputting to another ([bbc0e01d](https://github.com/thoughtram/clog/commit/bbc0e01dd3cc3d006fea1a029896a59eb1826c5a), closes [#63](https://github.com/thoughtram/clog/issues/63))
*   implements better errors, abstract writers, and defaults to stdout ([84507cc0](https://github.com/thoughtram/clog/commit/84507cc008ef53fbd3a20f87bc8f6029a7b87c68), closes [#58](https://github.com/thoughtram/clog/issues/58), [#57](https://github.com/thoughtram/clog/issues/57))

#### Performance

* **Regexs**  compiles regexs only once and gets more specific for increased performance ([2359c712](https://github.com/thoughtram/clog/commit/2359c7125ec04068d5c849522c4c4ed3ae345a71))

#### Bug Fixes

*   dep bug fix when parsing --from="" from command line ([32f8a15d](https://github.com/thoughtram/clog/commit/32f8a15d6ff11ab38397cf78d62fd2812ebb03a7))
```

That same result with the -T looks like this:

```
$ clog -T json
{"header":{"version":"","patch_version":false,"subtitle":null,"date":"2015-07-24"},"sections":[{"title":"Features","commits":[{"component":null,"subject":" implements a json writer output format","commit_link":"https://github.com/thoughtram/clog/commit/622770bff00cc95f2dfe8136e672681534d1acc1","closes":null},{"component":null,"subject":" adds performance as a default section","commit_link":"https://github.com/thoughtram/clog/commit/5003432279027b5ce4389a53baceb2f9fa790d20","closes":[{"issue":62,"issue_link":"https://github.com/thoughtram/clog/issues/62"}]},{"component":null,"subject":" allows reading old changelog data from one file and outputting to another","commit_link":"https://github.com/thoughtram/clog/commit/bbc0e01dd3cc3d006fea1a029896a59eb1826c5a","closes":[{"issue":63,"issue_link":"https://github.com/thoughtram/clog/issues/63"}]},{"component":null,"subject":" implements better errors, abstract writers, and defaults to stdout","commit_link":"https://github.com/thoughtram/clog/commit/84507cc008ef53fbd3a20f87bc8f6029a7b87c68","closes":[{"issue":58,"issue_link":"https://github.com/thoughtram/clog/issues/58"},{"issue":57,"issue_link":"https://github.com/thoughtram/clog/issues/57"}]}]},{"title":"Bug Fixes","commits":[{"component":null,"subject":" dep bug fix when parsing --from=\"\" from command line","commit_link":"https://github.com/thoughtram/clog/commit/32f8a15d6ff11ab38397cf78d62fd2812ebb03a7","closes":null}]},{"title":"Performance","commits":[{"component":"Regexs","subject":" compiles regexs only once and gets more specific for increased performance","commit_link":"https://github.com/thoughtram/clog/commit/2359c7125ec04068d5c849522c4c4ed3ae345a71","closes":null}]}]}
```

Or when running it through a pretty printer:

```json
$ clog -T json | python -m json.tool
{
    "header": {
        "date": "2015-07-24",
        "patch_version": false,
        "subtitle": null,
        "version": ""
    },
    "sections": [
        {
            "commits": [
                {
                    "closes": null,
                    "commit_link": "https://github.com/thoughtram/clog/commit/622770bff00cc95f2dfe8136e672681534d1acc1",
                    "component": null,
                    "subject": " implements a json writer output format"
                },
                {
                    "closes": [
                        {
                            "issue": 62,
                            "issue_link": "https://github.com/thoughtram/clog/issues/62"
                        }
                    ],
                    "commit_link": "https://github.com/thoughtram/clog/commit/5003432279027b5ce4389a53baceb2f9fa790d20",
                    "component": null,
                    "subject": " adds performance as a default section"
                },
                {
                    "closes": [
                        {
                            "issue": 63,
                            "issue_link": "https://github.com/thoughtram/clog/issues/63"
                        }
                    ],
                    "commit_link": "https://github.com/thoughtram/clog/commit/bbc0e01dd3cc3d006fea1a029896a59eb1826c5a",
                    "component": null,
                    "subject": " allows reading old changelog data from one file and outputting to another"
                },
                {
                    "closes": [
                        {
                            "issue": 58,
                            "issue_link": "https://github.com/thoughtram/clog/issues/58"
                        },
                        {
                            "issue": 57,
                            "issue_link": "https://github.com/thoughtram/clog/issues/57"
                        }
                    ],
                    "commit_link": "https://github.com/thoughtram/clog/commit/84507cc008ef53fbd3a20f87bc8f6029a7b87c68",
                    "component": null,
                    "subject": " implements better errors, abstract writers, and defaults to stdout"
                }
            ],
            "title": "Features"
        },
        {
            "commits": [
                {
                    "closes": null,
                    "commit_link": "https://github.com/thoughtram/clog/commit/2359c7125ec04068d5c849522c4c4ed3ae345a71",
                    "component": "Regexs",
                    "subject": " compiles regexs only once and gets more specific for increased performance"
                }
            ],
            "title": "Performance"
        },
        {
            "commits": [
                {
                    "closes": null,
                    "commit_link": "https://github.com/thoughtram/clog/commit/32f8a15d6ff11ab38397cf78d62fd2812ebb03a7",
                    "component": null,
                    "subject": " dep bug fix when parsing --from=\"\" from command line"
                }
            ],
            "title": "Bug Fixes"
        }
    ]
}
```

**Comment by cburgdorf** [comment]
That's super cool and exciting! Thanks for pushing things further!

>Personally I don't think it's worth the effort because the "fix" from the user standpoint is extremely simple, use the --from. Plus I don't think users would have a huge need to input one format and output another.

I fully agree with that.

So, it's only missing some adjustments to the docs before we can land this PR, right?

**Comment by kbknapp** [comment]
Yep, the docs are way out of whack becssue I went through a few different
iterations. Once I update the docs it'll be safe to merge if you guys are
good with the design and functionality.

**Comment by cburgdorf** [comment]
:+1:

**Comment by kbknapp** [comment]
I just updated all the docs. If @cburgdorf and @PascalPrecht are good with the implementation and design it's now safe to merge.

The basic design is this:

 * We expose a `SectionMap` which can be thought of an AST of sorts (although it's not set up like a full AST)
 * There is a trait called `FormatWriter` which contains a single method `write_changelog()` which accepts the "AST" or `SectionMap` that they can then to use write the changelog.
 * By default, `clog` provides two `FormatWriters` a `JsonWriter` and a `MarkdownWriter`
 * There is also a method in the `Clog` struct which allows writing of a changelog using any arbitrary `FormatWriter` which allows users to write their own formats and have the changelog written with those.

**Comment by kbknapp** [comment]
One last thing:

Since this a huge somewhat breaking change, and would push us to 1.0. If you feel it needs some "testing" time, I'd suggest a 1.0-beta, which can still make any changes required should we discover a flaw and go to 1.0-beta2, etc. Once we're sure it's a solid base with no (known) flaws can do a hard 1.0.

Just my thoughts :)

**Comment by cburgdorf** [comment]
Great job! I think it's ready to merge.

Regarding the breaking change and a `1.0` release. According the the [semver spec](http://semver.org/) one is free to do as many breaking changes as needed as long as we are still in the `0.x` phase.

>4.Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

>5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

So, I wouldn't worry about that and just release this as a new `0.x` release, fine tune if needed and then ship `1.0` as soon as we have a proper website for clog in place.

Thoughts?

**Comment by kbknapp** [comment]
I completely forgot that! Sounds good to me! :+1:

**Pull request merged**
