### PR TITLE
feat: split bin and lib

### PR DESCRIPTION
**Pull request by kbknapp**
~~**DO NOT MERGE**~~

The bin and lib are now split, but none of the docs have been written yet.

- [x] Split bin and lib
- [x] Add non-cli configuration options
- [x] redo the readme
- [x] add documentation

Relates to #44

### CODE REVIEW

**Comment by cburgdorf** [comment]
This looks like a good start. We should probably add an API similar to `from_matches` but with the focus on easy non CLI usage. Should we just merge this in first and then iterate on the library use case?

**Comment by kbknapp** [comment]
There are a few ways to easily configure it without a CLI; one using the builder pattern, and a second being accessing the fields directly (an unintentional bi-product of not having crate only visibility specifier).

i.e.
```rust
let mut clog = Clog::with_dir("/myproject").unwrap_or_else(|e| { println!("{}",e); std::process::exit(1); });
clog.repository("https://github.com/thoughtram/clog")
        .subtitle("Crazy Dog")
        .from("6d8183f")
        .version("0.1.0");
```

I also want to add a few more automatic methods which sort of do the work for you. Meaning, you can use `clog` just `src/bin/clog.rs` does where you access the sections and write them individually, or just call a single method or two and it does all the default work for you.

The commit I just pushed does a lot of the configuration help work, but it's not quite working yet - I need to troubleshoot a few things. I'll update once it's good to go.

**Comment by kbknapp** [comment]
Alright, it's working like normal now. 

Docs still need to be written though, so don't merge yet.

**Comment by kbknapp** [comment]
Those automatic changelog writing methods are done. For example, to write the `clog` changelog to an arbitrary location it's as simple as:

```rust
let mut clog = Clog::with_dir("/home/kevin/Projects/clog").unwrap_or_else(|e| { 
    println!("{}",e); 
    std::process::exit(1); 
});
clog.repository("https://github.com/thoughtram/clog")
    .subtitle("Crazy Dog")
    .from("6d8183f")
    .version("0.1.0");
clog.write_changelog_to("/home/kevin/clog_changelog.md")
```
Alternatively if I'd wanted to just use the current working dir and all the defaults just change `Clog::with_dir("/myproject")` -> `Clog::new()` and `clog.write_changelog_to("location")` -> `clog.write_changelog()`

**Comment by kbknapp** [comment]
Now it should be OK to merge (or test first, then merge :) ).

If you setup a github pages site, and just use this repo as the contents browsing to http://thoughtram.github.io/clog/ will re-direct to http://thoughtram/clog/docs/clog/index.html where the docs front page is located.

Clone the repo and use your browser to view `clog/docs/clog/index.html` to preview the docs.

Also, I put a makefile in there so you can do `make doc` which will auto-include the `README.md` as the doc front page but not clutter up `src/lib.rs`

**Comment by cburgdorf** [comment]
Thanks Kevin! That's awesome work. I'm about to release it as 0.8.0. Regarding the documentation. I'm in the process of setting up a site for clog where you can use clog right from the browser. It's a joint venture of nickel and clog working together :)

I'll probably finish it sometime next week and pick up the documentation task then to link to the docs from that site then. Btw, if you are into stickers and other swag I'd love to package some stuff up and send it over to you :) Just send me your address and t-shirt size via mail :)

**Comment by kbknapp** [comment]
That's an awesome idea, I'm looking forward to seeing this site! And yeah, I'll take you up on that offer thanks! :)

**Pull request merged**
