### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by kbknapp**
@thoughtram @vyp @cburgdorf 

I've updated `clog` and it's now compiling and working. I was having issues with `docopt` compiling so I switched to `clap` also I'm more familiar with `clap` since I maintain it. You still get the help/version/usage info for free  (just run `clog --help` for info). You can switch back to `docopt` once it's updated without much effort.

I ran it on this fork and it took 7ms to run...since I don't have any prior knowledge I'm not sure if that's a `+` or `-`

Hope this works for you! :)

### CODE REVIEW

**Comment by cburgdorf** [comment]
Wow, genius! This looks super cool. Also `clap` looks quite expressive, too! I'm currently running `rustup.sh` in order to review it properly. Thanks for the hard work!

**Comment by vyp** [comment]
Awesome! :) This compiles and works for me!

Just a small nitpick, looks like the `-r` flag is invalid. And also, the executable is built under `target/debug/`, not `target/`, which isn't an issue, just the readme might need updating.

And just for reference, I used:

    rustc 1.0.0-nightly (d8be84eb4 2015-03-29) (built 2015-03-30)
    cargo 0.0.1-pre-nightly (72f2af1 2015-03-29) (built 2015-03-29)

**Comment by cburgdorf** [comment]
@vyp the `-r` flag seems to work just fine for me? What issues did you run into?

Also this landed as https://github.com/thoughtram/clog/commit/d230dd8d323cc0edaebaa55e6a4b0e6a93e527ef

GREAT WORK!

**Comment by vyp** [comment]
@cburgdorf Oh nope, stand corrected! I was using `-r=`, which is why it was invalid.

**Comment by cburgdorf** [comment]
Aaaaand, we have the very first version of `clog` that was ever pushed to crates.io https://crates.io/crates/clog

*I'm so excited....and I just can't hide it :))*

**Comment by vyp** [comment]
Oh this is so great, nice! :D

**Pull request closed without merging**
