### PR TITLE
perf(Regexs): compiles regexs only once and gets more specific for in…

### PR DESCRIPTION
**Pull request by kbknapp**
…creased performance

On my machine running the example in the README.md goes from ~18-32ms down to ~8-10ms.

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@kbknapp that sounds awesome! How did you benchmark that?

**Comment by cburgdorf** [comment]
@PascalPrecht clog prints out the time it took to generate the changelog by default.

**Comment by kbknapp** [comment]
yeah I used the time clog prints out, but also I set up a tests module and used `cargo bench` to benchmark just the regex without all the file reading/writing.

**Comment by PascalPrecht** [comment]
This is cool, didn't know cargo has such a command!

**Comment by kbknapp** [comment]
Yep, its a super useful way to benchmark small items! :)

https://doc.rust-lang.org/book/benchmark-tests.html

**Pull request merged**
